//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RETouchResource.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RETouchResource.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00000000
        ///00001
        ///00001111
        ///000099
        ///00009999
        ///0000w
        ///5927499
        ///634252
        ///6911703
        ///701068
        ///721010
        ///7227545yfnfif
        ///77777777
        ///8888
        ///99999
        ///aaaa
        ///anothing
        ///bbbb
        ///beatles4
        ///BILLYRAY
        ///bprevatte
        ///browning
        ///bullmastiff
        ///burry
        ///ccccc
        ///cruiser
        ///DChrles
        ///dclxvi
        ///dddd
        ///deck
        ///Diver
        ///dzdzdzdz
        ///eagleone
        ///eeee
        ///gggg
        ///gordo
        ///growler
        ///gulf
        ///hakan
        ///Holt
        ///iiiii
        ///joel
        ///john
        ///leonard
        ///loopme
        ///markys
        ///MrBrown
        ///mustang0000
        ///neon2000
        ///OOOO
        ///poppop
        ///pussy
        ///shante
        ///stevie
        ///Strike34
        ///system
        ///tiger
        ///tincup
        ///wardota
        ///winston
        ///woody
        ///yyyyy
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_10_million_passw {
            get {
                return ResourceManager.GetString("retouch_10_million_passw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !@#$%
        ///!@#$%^
        ///!@#$%^&amp;
        ///!@#$%^&amp;*
        ///$100-a-plate dinner
        ///&amp;c
        ///&apos;cause
        ///&apos;cellist
        ///&apos;cello
        ///&apos;chute
        ///&apos;chutist
        ///&apos;copter
        ///&apos;d
        ///&apos;em
        ///&apos;gainst
        ///&apos;ll
        ///&apos;m
        ///&apos;mid
        ///&apos;midst
        ///&apos;mongst
        ///&apos;n
        ///&apos;prentice
        ///&apos;re
        ///&apos;s
        ///&apos;sblood
        ///&apos;sbodikins
        ///&apos;sdeath
        ///&apos;sfoot
        ///&apos;sheart
        ///&apos;shun
        ///&apos;slid
        ///&apos;slife
        ///&apos;slight
        ///&apos;snails
        ///&apos;strewth
        ///&apos;t
        ///&apos;til
        ///&apos;tis
        ///&apos;twas
        ///&apos;tween
        ///&apos;tween deck
        ///&apos;tween-decks
        ///&apos;twere
        ///&apos;twill
        ///&apos;twixt
        ///&apos;twould
        ///&apos;un
        ///&apos;varsity
        ///&apos;ve
        ///(audio-)visual
        ///(up)on
        ///*
        ///-
        ///-&apos;s
        ///-a
        ///-ability
        ///-able
        ///-ably
        ///-ac
        ///-acal
        ///-acea
        ///-aceae
        ///-acean
        ///-aceous
        ///-acious
        ///-a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_all3 {
            get {
                return ResourceManager.GetString("retouch_all3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advapi32;AbortSystemShutdown
        ///advapi32;AccessCheck
        ///advapi32;AccessCheckAndAuditAlarm
        ///advapi32;AddAccessAllowedAce
        ///advapi32;AddAce
        ///advapi32;AdjustTokenPrivileges
        ///advapi32;AllocateAndInitializeSid
        ///advapi32;AuditEnumerateCategories
        ///advapi32;BackupEventLog
        ///advapi32;BuildExplicitAccessWithName
        ///advapi32;BuildTrusteeWithSid
        ///advapi32;CertSrvIsServerOnline
        ///advapi32;CERT_CREDENTIAL_INFO
        ///advapi32;ChangeServiceConfig
        ///advapi32;ChangeServiceConfig2
        ///advapi32;CheckTokenMembership
        ///advapi32;ClearEventLog
        ///adva [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_apis_advapi32 {
            get {
                return ResourceManager.GetString("retouch_apis_advapi32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comctl32;CreatePropertySheetPage
        ///comctl32;DestroyPropertySheetPage
        ///comctl32;DoReaderMode
        ///comctl32;ImageList_Add
        ///comctl32;ImageList_AddMasked
        ///comctl32;ImageList_BeginDrag
        ///comctl32;ImageList_Create
        ///comctl32;ImageList_DragEnter
        ///comctl32;ImageList_DragLeave
        ///comctl32;ImageList_DragMove
        ///comctl32;ImageList_DragShowNolock
        ///comctl32;ImageList_DrawEx
        ///comctl32;ImageList_Duplicate
        ///comctl32;ImageList_EndDrag
        ///comctl32;ImageList_GetIcon
        ///comctl32;ImageList_GetIconSize
        ///comctl32;ImageList_SetIconSize
        ///comctl32 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_apis_comctl32 {
            get {
                return ResourceManager.GetString("retouch_apis_comctl32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comdlg32;ChooseFont
        ///comdlg32;CommDlgExtendedError
        ///comdlg32;FtpCommand
        ///comdlg32;GetOpenFileName
        ///comdlg32;GetSaveFileName
        ///comdlg32;NetShareAdd
        ///comdlg32;PageSetupDlg
        ///comdlg32;PrintDlg
        ///comdlg32;PrintDlgEx
        ///comdlg32;QueryPathOfRegTypeLib
        ///.
        /// </summary>
        public static string retouch_apis_comdlg32 {
            get {
                return ResourceManager.GetString("retouch_apis_comdlg32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypt32;CertAddEncodedCertificateToStore
        ///Crypt32;CertAlgIdToOID
        ///Crypt32;CertCloseStore
        ///Crypt32;CertCreateCertificateContext
        ///Crypt32;CertCreateCRLContext
        ///Crypt32;CertCreateCTLContext
        ///Crypt32;CertDuplicateStore
        ///Crypt32;CertEnumCertificatesInStore
        ///Crypt32;CertFindCertificateInCRL
        ///Crypt32;CertFindCertificateInStore
        ///Crypt32;CertFreeCertificateContext
        ///Crypt32;CertFreeCRLContext
        ///Crypt32;CertFreeCTLContext
        ///Crypt32;CertGetNameString
        ///Crypt32;CertNameToStr
        ///Crypt32;CertNameToStr
        ///Crypt32;CertOpenStore
        ///C [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_apis_crypt32 {
            get {
                return ResourceManager.GetString("retouch_apis_crypt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gdi32;AbortDoc
        ///gdi32;AbortPath
        ///gdi32;AddFontMemResourceEx
        ///gdi32;AddFontResource
        ///gdi32;AlphaBlend
        ///gdi32;AngleArc
        ///gdi32;AnimatePalette
        ///gdi32;Arc
        ///gdi32;ArcTo
        ///gdi32;BeginPath
        ///gdi32;BitBlt
        ///gdi32;CancelDC
        ///gdi32;CheckColorsInGamut
        ///gdi32;ChoosePixelFormat
        ///gdi32;Chord
        ///gdi32;CloseEnhMetaFile
        ///gdi32;CloseFigure
        ///gdi32;CloseMetaFile
        ///gdi32;ColorCorrectPalette
        ///gdi32;CombineRgn
        ///gdi32;CopyEnhMetaFile
        ///gdi32;CopyMetaFile
        ///gdi32;CreateBitmap
        ///gdi32;CreateBrushIndirect
        ///gdi32;CreateCompatibleBitmap
        ///gdi32;Cr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_apis_gdi32 {
            get {
                return ResourceManager.GetString("retouch_apis_gdi32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imm32;ImmConfigureIME
        ///imm32;ImmGetCompositionString
        ///imm32;ImmGetContext
        ///imm32;ImmGetConversionList
        ///imm32;ImmReleaseContext
        ///.
        /// </summary>
        public static string retouch_apis_imm32 {
            get {
                return ResourceManager.GetString("retouch_apis_imm32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kernel32;ActivateActCtx
        ///kernel32;ActiveActCtx
        ///kernel32;AddAtom
        ///kernel32;AddConsoleAlias
        ///kernel32;AddLocalAlternateComputerName
        ///kernel32;AllocateUserPhysicalPages
        ///kernel32;AllocConsole
        ///kernel32;APIGetVersionEx
        ///kernel32;AreFileApisANSI
        ///kernel32;AssignProcessToJobObject
        ///kernel32;AttachConsole,
        ///kernel32;AttachConsole
        ///kernel32;BackupRead
        ///kernel32;BackupWrite
        ///kernel32;Beep
        ///kernel32;BeginUpdateResource
        ///kernel32;BuildCommDCB
        ///kernel32;CancelIo
        ///kernel32;CheckRemoteDebuggerPresent
        ///kernel32;ClearComm [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_apis_kernel32 {
            get {
                return ResourceManager.GetString("retouch_apis_kernel32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mpr;DllImport
        ///mpr;ffgfdfdgffdfd
        ///mpr;MprAdminUserGetInfo
        ///mpr;MprAdminUserSetInfo
        ///mpr;MultinetGetConnectionPerformance
        ///mpr;VVNetAddConnection2
        ///mpr;WNetAddConnection
        ///mpr;WNetAddConnection2
        ///mpr;WNetAddConnection3
        ///mpr;WNetCancelConnection
        ///mpr;WNetCancelConnection2
        ///mpr;WNetCloseEnum
        ///mpr;WNetEnumResource
        ///mpr;WNetGetConnection
        ///mpr;WNetGetLastError
        ///mpr;WNetOpenEnum
        ///mpr;WNetUseConnection
        ///.
        /// </summary>
        public static string retouch_apis_mpr {
            get {
                return ResourceManager.GetString("retouch_apis_mpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netapi32;DsAddressToSiteNames
        ///Netapi32;DsEnumerateDomainTrusts
        ///Netapi32;DsGetDcClose
        ///Netapi32;DsGetDcName
        ///Netapi32;DsGetDcNext
        ///Netapi32;DsGetDcOpen
        ///Netapi32;DsGetDcSiteCoverage
        ///Netapi32;DsGetSiteName
        ///Netapi32;DsRoleFreeMemory
        ///Netapi32;DsRoleGetPrimaryDomainInformation
        ///Netapi32;LsaQueryInformationPolicy
        ///Netapi32;NetApiBufferAllocate
        ///Netapi32;NetApiBufferFree
        ///Netapi32;NetDfsAdd
        ///Netapi32;NetDfsEnum
        ///Netapi32;NetDfsGetClientInfo
        ///Netapi32;NetDfsGetClientInfo
        ///Netapi32;NetDfsGetInfo
        ///Netapi32;NetDf [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_apis_netapi32 {
            get {
                return ResourceManager.GetString("retouch_apis_netapi32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API (DLL) name;Func name
        ///.
        /// </summary>
        public static string retouch_apis_new_template {
            get {
                return ResourceManager.GetString("retouch_apis_new_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTDll;NtClose
        ///NTDll;NtCreateFile
        ///NTDll;NtGetContextThread
        ///NTDll;NtOpenDirectoryObject
        ///NTDll;NtOpenSymbolicLinkObject
        ///NTDll;NtQueryDirectoryObject
        ///NTDll;NtQueryInformationFile
        ///NTDll;NtQueryInformationProcess
        ///NTDll;NtQueryObject
        ///NTDll;NtQuerySymbolicLinkObject
        ///NTDll;NtQuerySystemInformation
        ///NTDll;NtQuerySystemTime
        ///NTDll;NtQueryTimerResolution
        ///NTDll;NtResumeProcess
        ///NTDll;NtSetSystemInformation
        ///NTDll;NtSetTimerResolution
        ///NTDll;NtSuspendProcess
        ///NTDll;NtUnmapViewOfSection
        ///NTDll;PROCESSINFOCLASS        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_apis_ntdll {
            get {
                return ResourceManager.GetString("retouch_apis_ntdll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ole32;BindMoniker
        ///ole32;BIND_OPTS
        ///ole32;CLIPFORMAT
        ///ole32;CLSIDFromProgID
        ///ole32;CLSIDFromProgIDEx
        ///ole32;CLSIDFromString
        ///ole32;CoAddRefServerProcess
        ///ole32;CoAllowSetForegroundWindow
        ///ole32;CoCancelCall
        ///ole32;CoCopyProxy
        ///ole32;CoCreateFreeThreadedMarshaler
        ///ole32;CoCreateGuid
        ///ole32;CoCreateInstance
        ///ole32;CoCreateInstanceEx
        ///ole32;CoDisableCallCancellation
        ///ole32;CoDisconnectObject
        ///ole32;CoDosDateTimeToFileTime
        ///ole32;CoEnableCallCancellation
        ///ole32;CoFileTimeNow
        ///ole32;CoFileTimeToDosDateTime
        ///ole3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_apis_ole32 {
            get {
                return ResourceManager.GetString("retouch_apis_ole32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oleaut32;GetActiveObject
        ///oleaut32;LoadTypeLib
        ///oleaut32;RegisterTypeLib
        ///oleaut32;SysFreeString
        ///oleaut32;SysStringLen
        ///oleaut32;UnRegisterTypeLib
        ///oleaut32;VarBstrFromDisp
        ///oleaut32;VariantChangeTypeEx
        ///oleaut32;VariantInit
        ///.
        /// </summary>
        public static string retouch_apis_oleaut32 {
            get {
                return ResourceManager.GetString("retouch_apis_oleaut32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shell32;api
        ///shell32;APPBARDATA
        ///shell32;APPBARDATA
        ///shell32;BatchExec
        ///shell32;CharSet
        ///shell32;CommandLineToArgvW
        ///shell32;CSIDL
        ///shell32;CSIDL
        ///shell32;dll ILCLONEFULL
        ///shell32;DllGetVersion
        ///shell32;DLLGETVERSIONINFO
        ///shell32;DoEnvironmentSubst
        ///shell32;DragAcceptFiles
        ///shell32;DragFinish
        ///shell32;DragQueryFile
        ///shell32;DragQueryPoint
        ///shell32;DuplicateIcon
        ///shell32;EnumFontFamExProc
        ///shell32;ERazMA
        ///shell32;ExtendedFileInfo
        ///shell32;ExtractAssociatedIcon
        ///shell32;ExtractIcon
        ///shell32;ExtractIconEx
        ///she [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_apis_shell32 {
            get {
                return ResourceManager.GetString("retouch_apis_shell32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shlwapi;AssocCreate
        ///shlwapi;AssocGetPerceivedType
        ///shlwapi;AssocQueryString
        ///shlwapi;ColorHLSToRGB
        ///shlwapi;ColorRGBToHLS
        ///shlwapi;HashData
        ///shlwapi;IPreviewHandler
        ///shlwapi;IsOS
        ///shlwapi;PathAddBackslash
        ///shlwapi;PathAppend
        ///shlwapi;PathBuildRoot
        ///shlwapi;PathCanonicalize
        ///shlwapi;PathCombine
        ///shlwapi;PathCommonPrefix
        ///shlwapi;PathCompactPath
        ///shlwapi;PathCompactPathEx
        ///shlwapi;PathCreateFromUrl
        ///shlwapi;PathFileExists
        ///shlwapi;PathFindNextComponent
        ///shlwapi;PathFindOnPath
        ///shlwapi;PathGetArgs
        ///shlwapi;Pa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_apis_shlwapi {
            get {
                return ResourceManager.GetString("retouch_apis_shlwapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comctl32;AbortDoc
        ///.
        /// </summary>
        public static string retouch_apis_template {
            get {
                return ResourceManager.GetString("retouch_apis_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user32;ActivateKeyboardLayout
        ///user32;AddClipboardFormatListener
        ///user32;AdjustWindowRect
        ///user32;AdjustWindowRectEx
        ///user32;AlignRects
        ///user32;AllowForegroundActivation
        ///user32;AllowSetForegroundWindow
        ///user32;AlphaWindow
        ///user32;AnimateWindow
        ///user32;AnyPopup
        ///user32;AppendMenu
        ///user32;ArrangeIconicWindows
        ///user32;AttachThreadInput
        ///user32;BeginDeferWindowPos
        ///user32;BeginPaint
        ///user32;BlockInput
        ///user32;Boshit
        ///user32;BringWindowToTop
        ///user32;BroadcastSystemMessage
        ///user32;BroadcastSystemMessageEx
        ///user3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_apis_user32 {
            get {
                return ResourceManager.GetString("retouch_apis_user32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version;GetFileVersionInfoSize
        ///.
        /// </summary>
        public static string retouch_apis_version {
            get {
                return ResourceManager.GetString("retouch_apis_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wininet;DeleteUrlCacheEntry
        ///wininet;DeleteUrlCacheGroup
        ///wininet;FindFirstUrlCacheEntry
        ///wininet;FindFirstUrlCacheGroup
        ///wininet;FindNextUrlCacheEntry
        ///wininet;FindNextUrlCacheGroup
        ///wininet;FtpCommand
        ///wininet;FtpCreateDirectory
        ///wininet;FtpDeleteFile
        ///wininet;FtpFindFirstFile
        ///wininet;FtpGetCurrentDirectory
        ///wininet;FtpGetFile
        ///wininet;FtpPutFile
        ///wininet;FtpRemoveDirectory
        ///wininet;FtpRenameFile
        ///wininet;FtpSetCurrentDirectory
        ///wininet;HttpOpenRequest
        ///wininet;HttpQueryInfo
        ///wininet;HttpSendRequest
        ///win [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_apis_wininet {
            get {
                return ResourceManager.GetString("retouch_apis_wininet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to winspool;AbortPrinter
        ///winspool;AddMonitor
        ///winspool;AddPrinter
        ///winspool;AddPrinterConnection
        ///winspool;ClosePrinter
        ///winspool;DeleteMonitor
        ///winspool;DeletePrinter
        ///winspool;DeletePrinterConnection
        ///winspool;DocumentProperties
        ///winspool;DRIVER_INFO_1
        ///winspool;DRIVER_INFO_2
        ///winspool;DRIVER_INFO_3
        ///winspool;DRIVER_INFO_5
        ///winspool;DRIVER_INFO_6
        ///winspool;DRIVER_INFO_8
        ///winspool;EndDocPrinter
        ///winspool;EndPagePrinter
        ///winspool;EnumJobs
        ///winspool;EnumMonitors
        ///winspool;EnumPorts
        ///winspool;EnumPrinterDrivers [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_apis_winspool {
            get {
                return ResourceManager.GetString("retouch_apis_winspool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to script;bat
        ///script;vbs
        ///script;js
        ///script;ps1
        ///script;py
        ///executable;exe
        ///executable;dll
        ///executable;com
        ///executable;pif
        ///executable;cmd
        ///executable;cpl
        ///executable;scr
        ///executable;ocx
        ///document;doc
        ///document;docx
        ///document;docm
        ///document;xls
        ///document;xlsx
        ///document;xlsm
        ///document;txt
        ///document;rtf
        ///document;pdf
        ///document;chm
        ///net-code;htm
        ///net-code;html
        ///net-code;asp
        ///net-code;aspx
        ///net-code;php
        ///net-code;css
        ///source-code;cs
        ///source-code;vb
        ///source-code;asm
        ///archive;zip
        ///archive;7z
        ///archive;rar
        ///archive;i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_filetypes {
            get {
                return ResourceManager.GetString("retouch_filetypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Char;Dec;Hex;Name;Ctrl Char
        ///;0;;;
        ///;1;;;
        ///;2;;;
        ///;3;;;
        ///;4;;;
        ///;5;;;
        ///;6;;;
        ///;7;;;
        ///;8;;;
        ///;9;;;
        ///;10;;;
        ///;11;;;
        ///;12;;;
        ///;13;;;
        ///;14;;;
        ///;15;;;
        ///;16;;;
        ///;17;;;
        ///;18;;;
        ///;19;;;
        ///;20;;;
        ///;21;;;
        ///;22;;;
        ///;23;;;
        ///;24;;;
        ///;25;;;
        ///;26;;;
        ///;27;;;
        ///;28;;;
        ///;29;;;
        ///;30;;;
        ///;31;;;
        ///;32;;;
        ///;33;;;
        ///;34;;;
        ///;35;;;
        ///;36;;;
        ///;37;;;
        ///;38;;;
        ///;39;;;
        ///;40;;;
        ///;41;;;
        ///;42;;;
        ///;43;;;
        ///;44;;;
        ///;45;;;
        ///;46;;;
        ///;47;;;
        ///;48;;;
        ///;49;;;
        ///;50;;;
        ///;51;;;
        ///;52;;;
        ///;53;;;
        ///;54;;;
        ///;55;;;
        ///;56;;;
        ///;57;;;
        ///;58;;;
        ///;59;;;
        ///;60;;;
        ///;61;; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_table_ascii {
            get {
                return ResourceManager.GetString("retouch_table_ascii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to templateID;templateName;itemPrefix;itemPostfix;itemSeparator
        ///1;VBScript template;ChrW(;);&quot;&quot;&quot; &amp; &quot;&quot;&quot;
        ///.
        /// </summary>
        public static string retouch_template {
            get {
                return ResourceManager.GetString("retouch_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to templateID;templateName;itemPrefix;itemPostfix;itemSeparator
        ///1;VBScript byte buffer template;ChrW(;);&quot;&quot;&quot; &amp; &quot;&quot;&quot;
        ///.
        /// </summary>
        public static string retouch_template__kopio {
            get {
                return ResourceManager.GetString("retouch_template__kopio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        ///1
        ///2
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///10
        ///11
        ///12
        ///13
        ///14
        ///15
        ///16
        ///17
        ///18
        ///19
        ///20
        ///21
        ///22
        ///23
        ///24
        ///25
        ///26
        ///27
        ///28
        ///29
        ///30
        ///31
        ///32
        ///33
        ///34
        ///35
        ///36
        ///37
        ///38
        ///39
        ///40
        ///41
        ///42
        ///43
        ///44
        ///45
        ///46
        ///47
        ///48
        ///49
        ///50
        ///51
        ///52
        ///53
        ///54
        ///55
        ///56
        ///57
        ///58
        ///59
        ///60
        ///61
        ///62
        ///63
        ///64
        ///65
        ///66
        ///67
        ///68
        ///69
        ///70
        ///71
        ///72
        ///73
        ///74
        ///75
        ///76
        ///77
        ///78
        ///79
        ///80
        ///81
        ///82
        ///83
        ///84
        ///85
        ///86
        ///87
        ///88
        ///89
        ///90
        ///91
        ///92
        ///93
        ///94
        ///95
        ///96
        ///97
        ///98
        ///99
        ///100
        ///101
        ///102
        ///103
        ///104
        ///105
        ///106
        ///107
        ///108
        ///109
        ///110
        ///111
        ///112
        ///113
        ///114
        ///115
        ///116
        ///117
        ///118
        ///119
        ///120
        ///121
        ///122
        ///123
        ///12 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_wordlist {
            get {
                return ResourceManager.GetString("retouch_wordlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSharp;using
        ///CSharp;&quot;System;&quot;
        ///CSharp;&quot;System.Collections.Generic;&quot;
        ///CSharp;&quot;System.Linq;&quot;
        ///CSharp;&quot;System.Text;&quot;
        ///CSharp;&quot;System.Threading.Tasks;&quot;
        ///CSharp;&quot;System.Diagnostics;&quot;
        ///CSharp;&quot;System.Drawing;&quot;
        ///CSharp;&quot;System.IO;&quot;
        ///CSharp;&quot;System.Runtime.Serialization.Formatters.Binary;&quot;
        ///CSharp;namespace
        ///CSharp;public
        ///CSharp;static
        ///CSharp;class
        ///CSharp;public
        ///CSharp;struct
        ///CSharp;string
        ///CSharp;override
        ///CSharp;return
        ///CSharp;enum
        ///CSharp;int
        ///CSharp;struct
        ///CSharp;byte[]
        ///CSharp;&quot;args;&quot;
        ///CSharp;new
        ///CShar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_wordlist_allscript {
            get {
                return ResourceManager.GetString("retouch_wordlist_allscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bat;ASSOC
        ///Bat;ATTRIB
        ///Bat;BREAK
        ///Bat;BCDEDIT
        ///Bat;CACLS
        ///Bat;CALL
        ///Bat;CD
        ///Bat;CHCP
        ///Bat;CHDIR
        ///Bat;CHKDSK
        ///Bat;CHKNTFS
        ///Bat;CLS
        ///Bat;CMD
        ///Bat;COLOR
        ///Bat;COMP
        ///Bat;COMPACT
        ///Bat;CONVERT
        ///Bat;COPY
        ///Bat;DATE
        ///Bat;DEL
        ///Bat;DIR
        ///Bat;DISKPART
        ///Bat;DOSKEY
        ///Bat;DRIVERQUERY
        ///Bat;ECHO
        ///Bat;ENDLOCAL
        ///Bat;ERASE
        ///Bat;EXIT
        ///Bat;FC
        ///Bat;FIND
        ///Bat;FINDSTR
        ///Bat;FOR
        ///Bat;FORMAT
        ///Bat;FSUTIL
        ///Bat;FTYPE
        ///Bat;GOTO
        ///Bat;GPRESULT
        ///Bat;GRAFTABL
        ///Bat;HELP
        ///Bat;ICACLS
        ///Bat;IF
        ///Bat;LABEL
        ///Bat;MD
        ///Bat;MKDIR
        ///Bat;MKLINK
        ///Bat;MODE
        ///Bat; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_wordlist_bat {
            get {
                return ResourceManager.GetString("retouch_wordlist_bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSharp;|=
        ///CSharp;+=
        ///CSharp;&lt;&lt;=
        ///CSharp;&gt;&gt;=
        ///CSharp;BinaryFormatter()
        ///CSharp;bool
        ///CSharp;break
        ///CSharp;byte
        ///CSharp;byte[]
        ///CSharp;case
        ///CSharp;catch
        ///CSharp;char
        ///CSharp;char[]
        ///CSharp;class
        ///CSharp;Close()
        ///CSharp;continue
        ///CSharp;else
        ///CSharp;enum
        ///CSharp;false
        ///CSharp;for
        ///CSharp;foreach
        ///CSharp;if
        ///CSharp;IndexOf
        ///CSharp;int
        ///CSharp;Length
        ///CSharp;List&lt;byte&gt;
        ///CSharp;List&lt;byte&gt;()
        ///CSharp;List&lt;int&gt;
        ///CSharp;List&lt;int&gt;()
        ///CSharp;List&lt;string&gt;
        ///CSharp;List&lt;string&gt;()
        ///CSharp;long
        ///CSharp;MemoryStream
        ///CShar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_wordlist_csharp {
            get {
                return ResourceManager.GetString("retouch_wordlist_csharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinWord;[Content_Types].xml
        ///WinWord;_rels/.rels
        ///WinWord;word/_rels/document.xml.rels
        ///WinWord;word/document.xml
        ///WinWord;word/footer1.xml
        ///WinWord;word/_rels/footer1.xml.rels
        ///WinWord;word/header1.xml
        ///WinWord;word/endnotes.xmlÄU
        ///WinWord;word/footnotes.xmlÄT
        ///WinWord;word/media/image1.png
        ///WinWord;word/theme/theme1.xml
        ///WinWord;word/settings.xml
        ///WinWord;word/styles.xml
        ///WinWord;word/numbering.xml
        ///WinWord;customXml/_rels/item1.xml.rels
        ///WinWord;customXml/itemProps1.xml
        ///WinWord;customXml/item1.xml
        ///WinW [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_wordlist_document_docx {
            get {
                return ResourceManager.GetString("retouch_wordlist_document_docx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jpeg
        ///.
        /// </summary>
        public static string retouch_wordlist_document_image {
            get {
                return ResourceManager.GetString("retouch_wordlist_document_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF;%PDF-1.5
        ///PDF;%%EOF
        ///PDF;%PDF-1.4
        ///PDF;%PDF-1.6
        ///PDF;/Ascent
        ///PDF;/AvgWidth
        ///PDF;/CapHeight
        ///PDF;/Contents
        ///PDF;/Descent
        ///PDF;/Encoding/WinAnsiEncoding/Type/Font&gt;&gt;
        ///PDF;/Filter/FlateDecode/Length
        ///PDF;/Filter/FlateDecode/N
        ///PDF;/Flags
        ///PDF;/FlateDecode&gt;&gt;
        ///PDF;/FontBBox[
        ///PDF;/FontName/Arial/FontFile2
        ///PDF;/ID
        ///PDF;/Info
        ///PDF;/Leading
        ///PDF;/Length
        ///PDF;/MaxWidth
        ///PDF;/MediaBox[
        ///PDF;/Predictor
        ///PDF;/Prev
        ///PDF;/Root
        ///PDF;/Size
        ///PDF;/StructTreeRoot
        ///PDF;/Type/ExtGState&gt;&gt;
        ///PDF;/Type/FontDescriptor/ItalicAng [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_wordlist_document_pdf {
            get {
                return ResourceManager.GetString("retouch_wordlist_document_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML;!DOCTYPE
        ///HTML;a
        ///HTML;abbr
        ///HTML;address
        ///HTML;area
        ///HTML;article
        ///HTML;aside
        ///HTML;audio
        ///HTML;b
        ///HTML;base
        ///HTML;bdi
        ///HTML;bdo
        ///HTML;blockquote
        ///HTML;body
        ///HTML;br
        ///HTML;button
        ///HTML;canvas
        ///HTML;caption
        ///HTML;cite
        ///HTML;code
        ///HTML;col
        ///HTML;colgroup
        ///HTML;datalist
        ///HTML;dd
        ///HTML;del
        ///HTML;details
        ///HTML;dfn
        ///HTML;dialog
        ///HTML;div
        ///HTML;dl
        ///HTML;dt
        ///HTML;em
        ///HTML;embed
        ///HTML;fieldset
        ///HTML;figcaption
        ///HTML;figure
        ///HTML;footer
        ///HTML;form
        ///HTML;h1
        ///HTML;h2
        ///HTML;h3
        ///HTML;h4
        ///HTML;h5
        ///HTML;h6
        ///HTML;head [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_wordlist_html {
            get {
                return ResourceManager.GetString("retouch_wordlist_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript;Array
        ///JavaScript;Boolean
        ///JavaScript;Date
        ///JavaScript;Error
        ///JavaScript;Function
        ///JavaScript;JSON
        ///JavaScript;Math
        ///JavaScript;Number
        ///JavaScript;Object
        ///JavaScript;RegExp
        ///JavaScript;String
        ///JavaScript;Map
        ///JavaScript;Set
        ///JavaScript;WeakMap
        ///JavaScript;WeakSet
        ///JavaScript;instanceof
        ///JavaScript;typeof
        ///JavaScript;new
        ///JavaScript;this
        ///JavaScript;do
        ///JavaScript;while
        ///JavaScript;for
        ///JavaScript;in
        ///JavaScript;of
        ///JavaScript;try
        ///JavaScript;catch
        ///JavaScript;let
        ///JavaScript;var
        ///JavaScript;const [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_wordlist_javascript {
            get {
                return ResourceManager.GetString("retouch_wordlist_javascript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell;function
        ///PowerShell;$file
        ///PowerShell;Test-Path
        ///PowerShell;Remove-Item
        ///PowerShell;Force
        ///PowerShell;Recurse
        ///PowerShell;return
        ///PowerShell;IntPtr
        ///PowerShell;Size
        ///PowerShell;Get-Item
        ///PowerShell;Value
        ///PowerShell;foreach
        ///PowerShell;in
        ///PowerShell;Get-Content
        ///PowerShell;throw
        ///PowerShell;Get-Host
        ///PowerShell;Get-Date
        ///PowerShell;WriteLine
        ///PowerShell;Select-Xml
        ///PowerShell;split-path
        ///PowerShell;join-path
        ///PowerShell;if
        ///PowerShell;try
        ///PowerShell;catch
        ///PowerShell;Start-Process
        ///PowerShell; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_wordlist_powershell {
            get {
                return ResourceManager.GetString("retouch_wordlist_powershell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python;py
        ///.
        /// </summary>
        public static string retouch_wordlist_python {
            get {
                return ResourceManager.GetString("retouch_wordlist_python", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedWord;Automation
        ///RedWord;Cain
        ///RedWord;CallNextHookEx
        ///RedWord;CallWindowProc
        ///RedWord;CallWindowProcA
        ///RedWord;CDO.Message
        ///RedWord;ExitProcess
        ///RedWord;FreeEnvironmentStrings
        ///RedWord;FreeLibrary
        ///RedWord;FreeSid
        ///RedWord;GetActiveWindow
        ///RedWord;GetCapture
        ///RedWord;GetCurrentThread
        ///RedWord;GetCurrentThreadId
        ///RedWord;GetKeyState
        ///RedWord;GetMessagePos
        ///RedWord;GetMessageTime
        ///RedWord;GetModuleFileName
        ///RedWord;GetModuleHandle
        ///RedWord;GetProcAddress
        ///RedWord;GetProcessVersion
        ///RedWord;GetVersionEx
        ///R [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_wordlist_redwords {
            get {
                return ResourceManager.GetString("retouch_wordlist_redwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoded VBScript;#@~^EAAAAA==
        ///Encoded VBScript;AA==
        ///Encoded VBScript;MAsFAA==o!x
        ///.
        /// </summary>
        public static string retouch_wordlist_vbe {
            get {
                return ResourceManager.GetString("retouch_wordlist_vbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBScript;&amp;chr(34)
        ///VBScript;&amp;chr(34)&amp;
        ///VBScript;&amp;chr(34)&amp;chr(34)&amp;
        ///VBScript;As
        ///VBScript;Asc(
        ///VBScript;Asc(
        ///VBScript;ByVal
        ///VBScript;CBool(
        ///VBScript;CDO.Message
        ///VBScript;CheckAccess
        ///VBScript;chr(34)
        ///VBScript;ChrW
        ///VBScript;CInt(
        ///VBScript;Class
        ///VBScript;Close
        ///VBScript;Const
        ///VBScript;CreateItem(
        ///VBScript;CreateKey
        ///VBScript;CreateObject
        ///VBScript;CreateObject(
        ///VBScript;CreateTextFile
        ///VBScript;DateAdd(
        ///VBScript;DateTime
        ///VBScript;DateTime.Value
        ///VBScript;DeleteKey
        ///VBScript;Dim
        ///VBScript;dim
        ///VBS [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_wordlist_vbscript {
            get {
                return ResourceManager.GetString("retouch_wordlist_vbscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !@#$%
        ///!@#$%^
        ///!@#$%^&amp;
        ///!@#$%^&amp;*
        ///$100-a-plate dinner
        ///&amp;c
        ///&apos;cause
        ///&apos;cellist
        ///&apos;cello
        ///&apos;chute
        ///&apos;chutist
        ///&apos;copter
        ///&apos;d
        ///&apos;em
        ///&apos;gainst
        ///&apos;ll
        ///&apos;m
        ///&apos;mid
        ///&apos;midst
        ///&apos;mongst
        ///&apos;n
        ///&apos;prentice
        ///&apos;re
        ///&apos;s
        ///&apos;sblood
        ///&apos;sbodikins
        ///&apos;sdeath
        ///&apos;sfoot
        ///&apos;sheart
        ///&apos;shun
        ///&apos;slid
        ///&apos;slife
        ///&apos;slight
        ///&apos;snails
        ///&apos;strewth
        ///&apos;t
        ///&apos;til
        ///&apos;tis
        ///&apos;twas
        ///&apos;tween
        ///&apos;tween deck
        ///&apos;tween-decks
        ///&apos;twere
        ///&apos;twill
        ///&apos;twixt
        ///&apos;twould
        ///&apos;un
        ///&apos;varsity
        ///&apos;ve
        ///(audio-)visual
        ///(up)on
        ///*
        ///-
        ///-&apos;s
        ///-a
        ///-ability
        ///-able
        ///-ably
        ///-ac
        ///-acal
        ///-acea
        ///-aceae
        ///-acean
        ///-aceous
        ///-acious
        ///-a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string retouch_wordlist_wechall {
            get {
                return ResourceManager.GetString("retouch_wordlist_wechall", resourceCulture);
            }
        }
    }
}
